### ISSUE TITLE
Validate proxy server tests

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#150]

**Comment by shinenelson** [comment]
the tests are all passing. what was missed was some documentation that was required to set the Airtable Base up ( this was documented in the pull request #133 though ). I'm guessing that the tests failing was because the Airtable Base was mis-configured. that was the only thing I could identify after looking at this.

I've added the documentation in f89fe7c describing the assumptions that are taken in the test suite and the minimum required fields that needs to be in the Airtable Base for the Airtable test suite to work.

**Comment by kavithaii** [comment]
@shinenelson Tests are failing.

**Comment by shinenelson** [comment]
there was a bug in the Airtable tests due to the incorrect request ( hiddenFormField ) being passed to the proxy-server. this has been fixed in 8f272ea.

**Comment by kavithaii** [comment]
@shinenelson, All test are passing. 

![image](https://user-images.githubusercontent.com/62616547/87912020-3b745a00-ca8a-11ea-8553-6dc07b14966f.png)
