### ISSUE TITLE
Split proxy server test into test data setup and test script

### ISSUE THREAD

**Issue by 5r1n1** [million-views/praas#87]
- The Proxy Server test script is a work-in-progress
- Currently it is a monolithic script with both resource server test data setup and proxy server testing
- Resource Server Test data setup should be taken out into a script of its own and placed under Resource server folder
- Currently all proxy server tests are directed to localhost:5000
- This should be changed by updating 'host' header in each test request to match with the test data
- Some test data include API keys. Though Airtable account test uses a fake id and test data, it is good practice to keep all sensitive data in .env files and not check them into github. Test data should be updated to implement this.

**Comment by shinenelson** [comment]
things to do as I see it :
[ ] split the setup of the backend server from the main test and move it into its own file
[ ] remove CURI update hack and make existing test for proxy server properly functional ( reference issue #86 )
[ ] separate out existing test data from within the test file
stretch
[ ] add more tests for hidden form field

**Comment by shinenelson** [comment]
I'm sorry for the commit spam. Following our discussions last evening, I've made the suggested changes from the feedback and gotten the situation to comparable level where I was earlier but this time, based on the suggestions from earlier.

here's where this is at : 
1. the test conduit setup has been moved from the proxy server test suite into the crud server test suite
2. of the remaining tests that have functional code, 1 pass and 2 fail. The reason for the failures are because the external services are being called and the corresponding services return a `HTTP 404`.

**Comment by kavithaii** [comment]
**1. Test cases Condition table **
**2. Finalize test cases **
3. Test data design (WIP)

**Comment by kavithaii** [comment]
@shinenelson Explain why the task has not been completed past the due date?
What is the next ETA for this task?
List the complete and pending sub-tasks

**Comment by shinenelson** [comment]
@kavithaii, this issue was technically completed with 5aaaed9 ( #94 ). however, I made a mis-assumption and continued to assume that I was working on this issue when I was actually working on #82 ( I messed up the issue titles in my head ).

( in my opinion, your comment from June 24, 2020 should also have gone to #82 )

while, commits `0fa3291..7c65034` also belong to #82, I mistakenly committed them with the wrong tracking issue number. I will be correcting that and pushing future commits with the correct issue number.
