### ISSUE TITLE
Replace archaic terminology in code and documents

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#93]
***Review all code/documents*** 
Eliminate the use of the following words: **blacklist, whitelist, master, slave**.
If you find the above terms take a few minutes of detour to change it.

- [Issue Reference](https://github.com/openssl/openssl/pull/12089)
- [Terminology, Power and Oppressive Language](https://tools.ietf.org/id/draft-knodel-terminology-00.html)

**Comment by m5nv** [comment]
16 hits in code for whitelist mostly in front-end, all emanating from the model and its description. @vakareeralil let me know if you want to take this since most of the changes are in front-end. If short on bandwidth I will take this up.

**Comment by electrofloat** [comment]
Issue should be closed like https://github.com/openssl/openssl/issues/12148 was, before it explodes.

I couldn't comment on https://github.com/openssl/openssl/pull/12089 because it is already locked, but if you change any of the **BLACK**list, whitelist, **MASTER**, **SLAVE** words, I'll be offended, and will request to change it back ASAP.

**Comment by aleksejrs** [comment]
Think of "BLACK" as what a place is when outside light DOES NOT go through the walls, and "WHITE" when light light DOES go through the walls.
