### ISSUE TITLE
Create 'Replace Conduit' API

### ISSUE THREAD

**Issue by 5r1n1** [million-views/praas#97]
- PUT to /conduits/_\<conduit id\>_ with conduit JSON as body
 - Respond 401 if auth failure
 - Respond 422 and error list if input validation fails
 - Respond 404 if no conduit found with id
 - Respond 200 and no response body if replace successful
 - Respond 422 and error list if replace conduit fails

**Comment by kavithaii** [comment]
@5r1n1 Explain why the task has past the due date? 
What is the next ETA for this task? 
List the complete and pending sub-tasks

**Comment by m5nv** [comment]
@shinenelson  it's possible that this has been implemented and needs tests. Please investigate and close if needed. Else, provide an estimate to complete.

**Comment by shinenelson** [comment]
the functionality was implemented in 5b7f06c by 5r1n1, however, it is not on in the working tree though ( GitHub reports that it _does not belong to any branch on this repository_ ). I'll have to manually pull the change into a branch and then create a pull request to put it on the working tree. Also, there aren't any tests for the code, so that needs to be implemented. I should be able to finish it by tomorrow.

**Comment by m5nv** [comment]
To clarify, the code is in the main. The GitHub message is most likely from the branch being deleted from where the code was taken from.  So this issue's scope is reduced to writing the test cases to test the PUT method.

**Comment by shinenelson** [comment]
I made a misguiding statement here that the changes were not on the working tree.
I'm correcting that - the changes are already on `master`.

I was looking for the specific commit mentioned on this issue which I couldn't find in the working tree. this was because I overlooked the fact that the changes could've been squashed in via a pull request. it was indeed squashed in via #123. I should've verified in the source code itself for the exact changes before making that statement; my bad.

what remains to be done here is to implement the test cases.
